In [1]:
##you can use this as a mini guide to learn or recap the absolute basics of numpy

# Array and its shape

In [4]:
#create an 1D array
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8]) 
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
#you can create a 2D array by wrapping around an extra [] bracket.
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
#we always need to find out the shape of an array, shape provides dimension of the array
print(a.shape)  
print(b.shape)

(8,)
(2, 4)


In [8]:
#let's create two random arrays of the following shape(2,4) and (4,2)

c = np.random.randint(0,9, size=(4,2))     # this will create a (4,2) array that contains integers between 0 to 9
d = np.random.randint(10,19, size=(4,3))   # this will create a (4,3) array that contains integers between 10 to 19
print(c)
print(d)

[[7 5]
 [4 4]
 [4 1]
 [7 3]]
[[12 10 16]
 [11 18 14]
 [17 17 16]
 [18 12 15]]


In [9]:
#you can stack both the arrays horizontally, as long as the number of the 1st dinesion(number of rows) matches, which is true in this case.

e = np.hstack((c,d))   # the new array will have the shape of (4,5)
e

array([[ 7,  5, 12, 10, 16],
       [ 4,  4, 11, 18, 14],
       [ 4,  1, 17, 17, 16],
       [ 7,  3, 18, 12, 15]])

In [10]:
#you can stack two arrays vertically, as long as the second dimension(number of columns) matches, which is not true in case of c and d.
#we can not stack vertically c and d, because the number of columns do not match.

#let's create a new array with a shape of (2,3)
f = np.random.randint(20,29,size=(2,3))
f

array([[20, 22, 21],
       [28, 22, 24]])

In [13]:
#we can stack d and f because the number of columns(the second dimension) matches.
g = np.vstack((d,f))
g

#we can also split an arrays horizontally or vertically by hsplit/vsplit syntax.

array([[12, 10, 16],
       [11, 18, 14],
       [17, 17, 16],
       [18, 12, 15],
       [20, 22, 21],
       [28, 22, 24]])

# Manipulating arrays (reshape)

In [16]:
#reshaping an array/matrix is an important aspects of deeplearning,
# let's start with flattening an array g, g was previously (6,3), after flattening it will be an 1D array(18,)
#h.flatten() can also be used as a syntax for this purpose

h = np.ravel(g)
print(h.shape)
h

(18,)


array([12, 10, 16, 11, 18, 14, 17, 17, 16, 18, 12, 15, 20, 22, 21, 28, 22,
       24])

In [17]:
#we can also reshape as array, as long as the dimensions are compatable, means all the elements must be utilzed in the array.
#a (10,10) array can be reshaped to (2,50) or (4,25), (5,20) or....so on.
# let's reshape the array g or h into a (2,9) shape.

i = g.reshape(2,9)
i

array([[12, 10, 16, 11, 18, 14, 17, 17, 16],
       [18, 12, 15, 20, 22, 21, 28, 22, 24]])

In [19]:
#you can provide one of the dimension and ask the computer to figure out the second dimension by itself.
# by providing -1, we are asking the computer to figure the other dimension automatically.
j = g.reshape(2,-1)
j

array([[12, 10, 16, 11, 18, 14, 17, 17, 16],
       [18, 12, 15, 20, 22, 21, 28, 22, 24]])

In [20]:
#Let's create a random 3d array of the following shape (3,2,2) and the convert it into a (3,4) array.
k = np.random.randint(1,30, size=(3,2,2))
print(k)


[[[ 7 16]
  [24  7]]

 [[17  7]
  [28  5]]

 [[ 2 12]
  [ 8  3]]]


In [21]:
l = k.reshape(3,4)
print(l)

[[ 7 16 24  7]
 [17  7 28  5]
 [ 2 12  8  3]]


# Indexing an array and accessing an index from an array

In [22]:
#it is a bit easier to visualize an index in a 2d array.Let's look at the array 'l' above as an example
#17 is at the 2nd row and 1st column of l. So its index should be [1,0]
#indexing begins at 0 and goes on from there. 0,1,2.. and so on
#for the array l, could you find the number for the following index:[2,2], the answer is 8, 3rd row and 3rd column
#lets see couple of more example with syntax.

print(l[2,2])


8


In [23]:
#take a look at the array 'k', and find the element that is present at (1,1,0), the answer would be 28
#you analyze one dimension at a time, remove the bracket one at a time from the outside.
print(k[1,1,0])

28


In [24]:
#you can create a new array from a given rows/columns

m = l[1,:]  #this means you are accessing 2nd row and all the numbers present in all the columns from the second row
m

array([17,  7, 28,  5])

In [25]:
n = l[:,3]  #this means you are accesing all the numbers from all the rows present in the 4th column
n

array([7, 5, 3])

In [27]:
#lets create an array of shape [10,5] and access all the elements of the first three row

o = np.random.randint(10,99, size=(10,5))
o

array([[53, 10, 17, 81, 23],
       [52, 13, 93, 59, 73],
       [52, 46, 73, 21, 96],
       [82, 52, 47, 34, 94],
       [94, 84, 84, 40, 17],
       [15, 28, 68, 41, 44],
       [68, 57, 43, 41, 96],
       [78, 19, 91, 47, 98],
       [47, 22, 49, 82, 51],
       [13, 68, 92, 58, 41]])

In [28]:
#first three row can be accessed by the following
print(o[:3])

#this is a handy tool to quickly glance at your large scale data to check if everything is working the way it is supposed to.


[[53 10 17 81 23]
 [52 13 93 59 73]
 [52 46 73 21 96]]


# Math operation with arrays

In [31]:
#regular math can be done as long as the shape of the arrays match
p = np.random.randint(10,50, size=(2,3))
q = np.ones((2,3))
print(p)
print(q)
#both of the arrays/matrices have the same shape[2,3]. which means we can do any math operations along the same indices.
r= p + q
print(r)

[[36 40 26]
 [45 45 49]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[37. 41. 27.]
 [46. 46. 50.]]


In [32]:
s= p*q
print(s)

[[36. 40. 26.]
 [45. 45. 49.]]


In [34]:
#matrix multiplication can be done as long as the number of columns matches with the number of rows of the next array.
#matrix multiplication between t(2,3) and u(3,5) will yield a (2,5) matrix, lets take a look
t = np.random.randint(0,9, size=(2,3))
u = np.random.randint(0,9, size=(3,5))

v = np.matmul(t,u)
print(v.shape)
v

(2, 5)


array([[42, 47, 35, 48, 27],
       [57, 65, 39, 70, 33]])